'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProxyGeneratorV2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://azenv.net.
        '''</summary>
        Friend ReadOnly Property Judge() As String
            Get
                Return ResourceManager.GetString("Judge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+.
        '''</summary>
        Friend ReadOnly Property Matches() As String
            Get
                Return ResourceManager.GetString("Matches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nothing to save!.
        '''</summary>
        Friend ReadOnly Property PGV2_1() As String
            Get
                Return ResourceManager.GetString("PGV2_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please load proxies to check first!.
        '''</summary>
        Friend ReadOnly Property PGV2_2() As String
            Get
                Return ResourceManager.GetString("PGV2_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please either use inbuilt sources or provide your own..
        '''</summary>
        Friend ReadOnly Property PGV2_3() As String
            Get
                Return ResourceManager.GetString("PGV2_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished! Saving output....
        '''</summary>
        Friend ReadOnly Property PGV2_4() As String
            Get
                Return ResourceManager.GetString("PGV2_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program terminated!.
        '''</summary>
        Friend ReadOnly Property PGV2_5() As String
            Get
                Return ResourceManager.GetString("PGV2_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nothing to copy!.
        '''</summary>
        Friend ReadOnly Property PGV2_6() As String
            Get
                Return ResourceManager.GetString("PGV2_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copied!.
        '''</summary>
        Friend ReadOnly Property PGV2_7() As String
            Get
                Return ResourceManager.GetString("PGV2_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proxies loaded!.
        '''</summary>
        Friend ReadOnly Property PGV2_pLoad() As String
            Get
                Return ResourceManager.GetString("PGV2_pLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sources loaded!.
        '''</summary>
        Friend ReadOnly Property PGV2_sLoad() As String
            Get
                Return ResourceManager.GetString("PGV2_sLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to txt files (*.txt)|*.txt.
        '''</summary>
        Friend ReadOnly Property PGV2_TxtFile() As String
            Get
                Return ResourceManager.GetString("PGV2_TxtFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $http://50kproxies.com/10-february-10-02-new-fresh-daily-50000-proxy-list-50kproxies-com/
        '''$http://50kproxies.com/11-january-11-01-new-fresh-daily-50000-proxy-list-50kproxies-com/
        '''$http://50na50.net/
        '''$http://50na50.net/proxy/httplist
        '''$http://50na50.net/no_anonim_http.txt
        '''$http://aliveproxy.com/anonymous-proxy-list
        '''$http://aliveproxy.com/ca-proxy-list
        '''$http://aliveproxy.com/de-proxy-list
        '''$http://aliveproxy.com/fastest-proxies
        '''$http://aliveproxy.com/fr-proxy-list
        '''$http://aliveproxy.com/gb-proxy-list        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property psrc() As String
            Get
                Return ResourceManager.GetString("psrc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $.
        '''</summary>
        Friend ReadOnly Property SplitString() As String
            Get
                Return ResourceManager.GetString("SplitString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HTTP_HOST = azenv.net.
        '''</summary>
        Friend ReadOnly Property TestString() As String
            Get
                Return ResourceManager.GetString("TestString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.2 Safari/537.36.
        '''</summary>
        Friend ReadOnly Property UserAgent() As String
            Get
                Return ResourceManager.GetString("UserAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://pastebin.com/raw/KhiFJE4m.
        '''</summary>
        Friend ReadOnly Property WebSrc() As String
            Get
                Return ResourceManager.GetString("WebSrc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
